import './assets/styles/style.scss';
import './views/article/article.ts';
import './views/articles/articles.ts';
import './views/countdown/countdown.ts';
import './views/layout/layout.ts';
import './views/layout-404/layout-404.ts';
import './views/login/login.ts';
import './views/poll/poll.ts';
import './views/profile/profile.ts';
